baseURL: "https://amalroshan.netlify.app/projects/"
languageCode: en-us
title: Portfolio
theme: ["PaperMod"]
pagination:
  pagerSize: 10



buildDrafts: false


params:
  title: Portfolio
  description: "This is a portfolio website"
  keywords: [Blog, Portfolio]
  author: Amal Roshan P
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: x
      url: "https://x.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/"

menu:
  main:
    - identifier: projects
      name: projects
      url: /projects/
      weight: 10




